check tree_model valid in contribute_to_class();
same time tree_model is None:

```python
AttributeError: 'NoneType' object has no attribute '_tree_manager'
```